# takes the most recent commit on main, bumps version based on
# semver_component input, pushes changes back to main, and publishes
# new version to PyPI
name: Bump version and publish to Internal Artifactory

on:
  workflow_dispatch:
    inputs:
      semver_component:
        description: "Semantic versioning component to bump (must be one of {major, minor, patch, dev})"
        required: true

# needed to grab org secrets for artifactory publish
# remove when switching to pypi
env:
  ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

jobs:
  publish:
    name: Bump and publish
    runs-on: [self-hosted, build]
    environment: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build bumpver twine

      - name: Bump version
        run: |
          git checkout main
          git config --global user.name 'aicsgithub'
          git config --global user.email 'aicsgithub@alleninstitute.org'
          python publish_bumpver_handler.py ${{ inputs.semver_component }}

      - name: Build Package
        run: |
          python -m build

      - name: Publish to Artifactory
        env:
          TWINE_USERNAME: ${{ secrets.ARTIFACTORY_USER }}
          TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          TWINE_NON_INTERACTIVE: true
        run: twine upload --verbose --repository-url='https://artifactory.corp.alleninstitute.org/artifactory/api/pypi/pypi-release-local' dist/*

      - name: Push changes
        run: |
          git push origin main
          git push origin --tags
      